### ISSUE TITLE
Epic - Profile Screen

### ISSUE THREAD

**Issue by DmnUAll** [DmnUAll/iOS-FakeNFT-StarterProject-Public#48]
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/6
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/7
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/8
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/9 
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/10
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/11
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/12
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/13
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/14 
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/15
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/16
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/17 
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/18
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/19
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/20
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/21
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/22
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/23 
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/24
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/51
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/52
- [x]  https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/55
- [x] https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/56
