### ISSUE TITLE
Epic - Catalog Screen

### ISSUE THREAD

**Issue by KirillShakurov** [DmnUAll/iOS-FakeNFT-StarterProject-Public#49]
- [x] [Create Models for NFT Collections](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/32)

- [x] [Create Models for individual NFTs](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/33)

- [x] [Create Catalog Screen using UITableView](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/34)

- [x] [Create a table cell to display information about each collection](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/35)

- [x] [Create sort button](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/36)

- [x] [Implement data loading for NFT catalog](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/37)

- [x] [Display a loading indicator on the catalog screen](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/38)

- [x] [Implement handling of clicking on a catalog cell to go to the screen of the selected NFT collection](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/39)

- [x] [Create an NFT collection screen displaying information about the selected collection](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/40)

- [x] [Create UICollectionView to display information about NFT](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/41)

- [x] [Implement the opening of the site of the author of the collection](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/42)

- [x] [Implement functionality to add NFT to favorites when clicking on a button](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/43)

- [x] [Update the appearance of the button to show the current state (favorite or not)](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/44)

- [x] [Implement functionality to add or remove NFTs from the cart](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/45)

- [x] [Update the appearance of the button to display the current state (added to cart or not)](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/46)
