### ISSUE TITLE
Epic - Cart Screen

### ISSUE THREAD

**Issue by icydtw** [DmnUAll/iOS-FakeNFT-StarterProject-Public#50]
- [ ] [Create a Cart Screen UI](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/25)
- [ ] [Create a custom cell for CartCollectionView (Cart Screen)](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/26)
- [ ] [Change the logic of the default NavigationController when a Cart Screen tab is selected](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/28)
- [ ] [Implement the Cart Screen logic](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/30)
- [ ] [Implement CartCollectionView cell logic (Cart Screen)](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/27)
- [ ] [Creating the logic for the filter button](https://github.com/DmnUAll/iOS-FakeNFT-StarterProject-Public/issues/31)
